# Generated by Django 4.0.4 on 2022-04-16 04:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
