# Generated by Django 4.0.4 on 2022-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_user_ms', '0003_alter_profile_description_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
